CREATE TABLE "Space" (
    "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL UNIQUE,
    "mapId" UUID NOT NULL REFERENCES "Map"("id") ON DELETE RESTRICT ON UPDATE CASCADE,    
    "creatorId" UUID NOT NULL REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
